# Generated by Django 5.1.dev20240306045047 on 2024-04-08 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=3000)),
                ('image', models.ImageField(upload_to='uploads/post/')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='uploads/post/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='uploads/post/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='uploads/post/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='uploads/post/')),
                ('check_1', models.BooleanField(default=False)),
                ('step_1', models.TextField(default='')),
                ('code_1', models.TextField(default='')),
                ('check_2', models.BooleanField(default=False)),
                ('step_2', models.TextField(blank=True, default='', null=True)),
                ('code_2', models.TextField(blank=True, default='', null=True)),
                ('check_3', models.BooleanField(default=False)),
                ('step_3', models.TextField(blank=True, default='', null=True)),
                ('code_3', models.TextField(blank=True, default='', null=True)),
                ('check_4', models.BooleanField(default=False)),
                ('step_4', models.TextField(blank=True, default='', null=True)),
                ('code_4', models.TextField(blank=True, default='', null=True)),
                ('check_5', models.BooleanField(default=False)),
                ('step_5', models.TextField(blank=True, default='', null=True)),
                ('code_5', models.TextField(blank=True, default='', null=True)),
                ('check_6', models.BooleanField(default=False)),
                ('step_6', models.TextField(blank=True, default='', null=True)),
                ('code_6', models.TextField(blank=True, default='', null=True)),
                ('check_7', models.BooleanField(default=False)),
                ('step_7', models.TextField(blank=True, default='', null=True)),
                ('code_7', models.TextField(blank=True, default='', null=True)),
                ('check_8', models.BooleanField(default=False)),
                ('step_8', models.TextField(blank=True, default='', null=True)),
                ('code_8', models.TextField(blank=True, default='', null=True)),
                ('check_9', models.BooleanField(default=False)),
                ('step_9', models.TextField(blank=True, default='', null=True)),
                ('code_9', models.TextField(blank=True, default='', null=True)),
                ('source_code', models.URLField(blank=True, max_length=10000, null=True)),
                ('upload_in', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insights.category')),
            ],
            options={
                'ordering': ('-upload_in',),
            },
        ),
    ]
