# Generated by Django 5.1.dev20240306045047 on 2024-04-08 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_1',
            new_name='image_5',
        ),
    ]
