# Generated by Django 5.1.dev20240306045047 on 2024-04-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0002_rename_image_1_post_image_5'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
